"""add_delivery_zones_table

Revision ID: 0c01bcc6f5a6
Revises: a1b2c3d4e5f6
Create Date: 2026-03-24 21:37:51.173447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c01bcc6f5a6'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create delivery_zones table
    op.create_table(
        'delivery_zones',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('shop_id', sa.UUID(), nullable=False),
        sa.Column('zone_type', sa.String(20), server_default='radius', nullable=False),
        sa.Column('center_lat', sa.Float(), nullable=False),
        sa.Column('center_lng', sa.Float(), nullable=False),
        sa.Column('radius_km', sa.Float(), nullable=True),
        sa.Column('polygon_coords', sa.JSON(), nullable=True),
        sa.Column('fee', sa.Float(), nullable=False, server_default='0'),
        sa.Column('free_above', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_delivery_zones_shop_id', 'delivery_zones', ['shop_id'])

    op.drop_index(op.f('idx_deals_expires'), table_name='deals', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_orders_customer'), table_name='orders')
    op.drop_index(op.f('idx_orders_shop_status'), table_name='orders')
    op.drop_index(op.f('idx_price_history_product'), table_name='price_history')
    op.create_index(op.f('ix_price_history_product_id'), 'price_history', ['product_id'], unique=False)
    op.drop_index(op.f('idx_products_attributes'), table_name='products', postgresql_using='gin')
    op.drop_index(op.f('idx_products_fts'), table_name='products', postgresql_using='gin')
    op.drop_index(op.f('idx_products_price'), table_name='products', postgresql_where='(is_available = true)')
    op.drop_index(op.f('idx_products_shop_category'), table_name='products', postgresql_where='(is_available = true)')
    op.drop_index(op.f('idx_search_logs_time'), table_name='search_logs')
    op.drop_index(op.f('idx_user_events_user'), table_name='user_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop delivery_zones table and related indexes
    op.drop_index('ix_delivery_zones_shop_id', table_name='delivery_zones')
    op.drop_table('delivery_zones')

    op.create_index(op.f('idx_user_events_user'), 'user_events', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_search_logs_time'), 'search_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_products_shop_category'), 'products', ['shop_id', 'category'], unique=False, postgresql_where='(is_available = true)')
    op.create_index(op.f('idx_products_price'), 'products', ['price'], unique=False, postgresql_where='(is_available = true)')
    op.create_index(op.f('idx_products_fts'), 'products', [sa.literal_column("to_tsvector('english'::regconfig, (COALESCE(name, ''::character varying)::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_products_attributes'), 'products', ['attributes'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_price_history_product_id'), table_name='price_history')
    op.create_index(op.f('idx_price_history_product'), 'price_history', ['product_id', 'changed_at'], unique=False)
    op.create_index(op.f('idx_orders_shop_status'), 'orders', ['shop_id', 'status'], unique=False)
    op.create_index(op.f('idx_orders_customer'), 'orders', ['customer_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_deals_expires'), 'deals', ['expires_at'], unique=False, postgresql_where='(is_active = true)')
    # ### end Alembic commands ###
